CREATE TABLE Persons
(
PersonID INT IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
Salary DECIMAL(8,2),
PassportID INT UNIQUE
)

CREATE TABLE Passports
(
PassportID INT IDENTITY(101,1),
PassportNumber VARCHAR(100) NOT NULL
)

ALTER TABLE Passports
ADD CONSTRAINT PK_Passports
PRIMARY KEY (PassportID)

ALTER TABLE Persons
ADD CONSTRAINT PK_Persons
PRIMARY KEY (PersonID)

ALTER TABLE Persons
ADD CONSTRAINT FK_Persons_Passports
FOREIGN KEY (PassportID)
REFERENCES Passports(PassportID)

INSERT INTO Passports
VALUES ('N34FG21B'),
       ('K65LO4R7'),
	   ('ZE657QP2')

INSERT INTO Persons
VALUES ('Roberto', 43300.00, 102),
       ('Tom', 56100.00, 103),
	   ('Yana', 60200.00, 101)