ALTER TABLE Users
DROP CONSTRAINT PK_UserId

ALTER TABLE Users
ADD CONSTRAINT PK_UserId
PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT UQ_Username
UNIQUE (Username) 

ALTER TABLE Users
ADD CONSTRAINT checkLen
CHECK (len(Username) >= 3)